### ISSUE TITLE
The plugins `esys_flutter_share` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by itsAmitGoyani** [esysberlin/esys-flutter-share#95]
After upgrading flutter to 2.5.0, I'm getting below warning.
_The plugins `esys_flutter_share` use a deprecated version of the Android embedding. 
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration._

**To Reproduce**
1. Add this plugin to pubspec.yaml file of Flutter project.
2. Run 'flutter pub get' command.

**Comment by cihadturhan** [comment]
This repository is dead.
I've updated flutter and android dependencies in my repo.
Use it like
```yaml
esys_flutter_share:
    git:
      url: https://github.com/cihadturhan/esys-flutter-share.git
      ref: nullsafety+embedding-2
```
